### ISSUE TITLE
Support Hooks?

### ISSUE THREAD

**Issue by ssfrr** [JunoLab/Atom.jl#140]
Would a PR be merged to support hooks as described in [this issue comment](https://github.com/timholy/Revise.jl/pull/287#issuecomment-484144784)? Sounds like @timholy is game, but first I'd need to add the init hook to Atom.jl. If you're on-board than I'll get [Hooks.jl](https://github.com/ssfrr/hooks.jl) documented and published, then open the PR here.

**Comment by pfitzseb** [comment]
Sure, I'd be on board with that.

Would probably be best to add hook notifiers in various places here so that Revise can listen to those directly, instead of calling it's own setup code (which is quite hacky).

Couple things worth thinking about in the context of Hooks.jl:
- Would it make sense to support some matching rules, so that we could notify `juno-eval-repl` and `juno-eval-editor`, but Revise could register `juno-eval-*` or something like that? That example is kinda contrived, but it might be convenient to have that.
- In theory Revise wants to hook into any "eval-like" function, no matter whata package provides that. Maybe it would make sense to have some global events to listen to? Probably too hard to organize properly though.

**Comment by timholy** [comment]
This is probably not necessary anymore, now that we have `ast_transforms`. See https://github.com/timholy/Revise.jl/pull/425

**Comment by ssfrr** [comment]
Great news. Closing...
