### ISSUE TITLE
Questions for calling `serve` and `connect` outside of Atom

### ISSUE THREAD

**Issue by lihebi** [JunoLab/Atom.jl#198]
Hi,

I'm trying to write `goto-symbol` for Emacs, by using Atom.jl as backend. To do that, I'll need to start the server outside of Atom.

I'm trying to start the sever by:

```julia
using Atom
serve(5601)
connect(5602)
```

On Emacs side, I connect to 5601 for sending RPC and listen on 5602. Both connections work fine. I can send the **first** message (e.g. "ping") and get result (e.g. "pong"). However, only the **first** message works.

A closer look at the implementation, these two APIs looks strange to me. In the [definition of `serve` and `connect`](https://github.com/JunoLab/Atom.jl/blob/master/src/comm.jl#L92-L114), both functions mutate the global variable `sock`, via `global sock = ...`. As a result, only the **first** message works. Further messages do not get responses, simply because the sock is overwritten by the `connect` function, thus no longer listening to incoming traffic.

Is this behavior is intended? If so, what is the preferred way to invoke the server outside of Atom? Putting `serve` inside a loop?

--
Hebi

**Comment by lihebi** [comment]
Just realize that the socket is bidirectional. It's working now. Closing this.

**Comment by pfitzseb** [comment]
Right, `serve` and `connect` are mutually exclusive. Which one you should use depends on where you want to start the server.

Regarding your original goal: It might be easier to use LanguageServer.jl for this since the LSP is pretty well documented. That said, if you only want `goto-symbol` then Atom.jl's interface should be fairly straightforward as well.

Good luck and let us know how it goes!

**Comment by aviatesk** [comment]
@lihebi I would also like to know how your work goes ! Feel free to ask me if you feel unsure of like how to call functions / update symbol caches :)
