### ISSUE TITLE
readline(STDIN)  freezes julia

### ISSUE THREAD

**Issue by musm** [JunoLab/Atom.jl#44]
If in a script I have
`readline(STDIN)`
causes the julia console in atom to hang

**Comment by MikeInnes** [comment]
This isn't actually a freeze, it's just that Julia is waiting for input over the STDIN stream and none is coming – because Juno isn't a terminal.

You can fix this by selecting some text and running the `send to stdin` command. Alternatively, if the aim is to get some user input, use the `input()` function.

**Comment by Datseris** [comment]
Wooohoooo Thanks for the `input` function! Exactly what I was looking for!

**Comment by Helveg** [comment]
I'm encountering the freeze with both the readline and input functions, any ideas?

**Comment by pfitzseb** [comment]
Yeah, that's pretty annoying. See https://github.com/JunoLab/Juno.jl/issues/118 for a "workaround".
